# Generated by Django 6.1.1 on 2026-09-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('numero', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=10)),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_code_rider.conductor')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='app_code_rider.empresa'),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('conductores', models.ManyToManyField(related_name='rutas', to='app_code_rider.conductor')),
            ],
        ),
    ]
